
<script>

	$(document).ready(function() {

		
		 $("#saveProfissinal").click(function (){					
			
			//Carrega os dados do formulário
			var dadosForm = arrayToObject( $('#frmUsuarios').serializeArray() );

			///-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
			$.ajax({
				url: "/admin_usuarios/salvar",
				data: {dadosForm: dadosForm},
				dataType: "json",
				type: "POST",
				success: function(source){
					$.map(source, function (val,i){
					   if(i == 'sucesso'){
						   window.location.href = '/admin_usuarios';
					   } 
					});
					tratarMsgRetorno(source);
				},
				error: function(){
					$().msgbox("erro", "Desculpe! Não foi possível realizar a operação solicitada.");
				}
			});
			///-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
			
			
		});


	});
<?php
	//$this->dados["admin_id"] = 1 ;
?>

</script>


<div class="row page-title clearfix">
    <div class="page-title-left">
        <h5 class="mr-0 mr-r-5">Unidades</h5>
    </div>
</div>
<div class="widget-list">
  <div class="row">
      <div class="col-md-12 widget-holder">
          <div class="widget-bg">
              <div class="widget-body clearfix">
                  <h5 class="box-title mr-b-0">Dados Pessoais</h5>
                  <form id="frmUsuarios" name="frmUsuarios">
                  		<input type="hidden" name="admin_id" id="admin_id" readonly="readonly" value="<?php echo (isset($this->dados["admin_id"]) && $this->dados["admin_id"] > 0)?$this->dados["admin_id"]:"0"?>"/>
                      <div class="form-group row">
                          <label class="col-md-3 col-form-label" for="admin_nome">Nome</label>
                          <div class="col-md-9">
                              <input class="form-control" placeholder="" type="text" id="admin_nome" name="admin_nome" value="<?php echo (isset($this->dados["admin_nome"]))?$this->dados["admin_nome"]:""?>">
                          </div>
                      </div>
                      <div class="form-group row">
                          <label class="col-md-3 col-form-label" for="admin_email">E-mail</label>
                          <div class="col-md-9">
                              <input class="form-control" placeholder="" type="text" id="admin_email" name="admin_email" value="<?php echo (isset($this->dados["admin_email"]))?$this->dados["admin_email"]:""?>">
                          </div>
                      </div>
                      <h5 class="box-title mr-b-0">Acesso</h5>
                      <div class="form-group row">
                          <label class="col-md-3 col-form-label" for="admin_usuario">Usuário</label>
                          <div class="col-md-9">
                              <input class="form-control" placeholder="" type="text" id="admin_usuario" name="admin_usuario" value="<?php echo (isset($this->dados["admin_usuario"]))?$this->dados["admin_usuario"]:""?>">
                          </div>
                      </div>
                      <div class="form-group row">
                          <label class="col-md-3 col-form-label" for="admin_status">Status</label>
                          <div class="col-md-9">
                          		<select class="form-control" name="admin_status" id="admin_status">
																	<option value="Ativo" <?php echo (isset($this->dados["admin_status"]) && $this->dados["admin_status"] == 'Ativo')?"selected='selected'":""?>>Ativo</option>
																	<option value="Bloqueado" <?php echo (isset($this->dados["admin_status"]) && $this->dados["admin_status"] == 'Bloqueado')?"selected='selected'":""?>>Bloqueado</option>
															</select>
                          </div>
                      </div>
                      <div class="form-group row">
                          <label class="col-md-3 col-form-label" for="admin_senha">Senha</label>
                          <div class="col-md-9">
                              <input class="form-control" placeholder="" type="password" id="admin_senha" name="admin_senha">
                          </div>
                      </div>
                      <div class="form-actions">
                          <div class="form-group row">
                              <div class="col-md-9 ml-md-auto btn-list">
                                  <button class="btn btn-primary btn-rounded" type="button" id="saveProfissinal">Salvar</button>
                                  <button class="btn btn-outline-default btn-rounded" type="button" onclick="window.location.href = '/admin_usuarios'">Cancelar</button>
                              </div>
                          </div>
                      </div>
                  </form>
              </div>
              <!-- /.widget-body -->
          </div>
          <!-- /.widget-bg -->
      </div>
  </div>
</div>

<script>

$(function(){
});
</script>
