<?php 
//Valida a permissão de Visualização
//if($this->permissao["status"] == false){
//    echo '<p class="msgPermissao alerta">'.$this->permissao["mensagem"].'</p>';
//}else{
   
?>

<script>

	$(function(){
        $('#data_para_day').datepicker({
          dateFormat: 'dd/mm/yy',
           dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
           dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
           dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
           monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
           monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
           nextText: 'Proximo',
           prevText: 'Anterior'
        });
        
        $("#data_para_hour").mask("99:99");

        $('#salvarMetasprofissionais').click(function (e){
			e.preventDefault();
			
			var dadosForm = arrayToObject( $('form[id^="frmMetasprofissionais"]').serializeArray() );

			$.ajax({
				url: "/metasprofissionais/salvar",
				data: {dadosForm: dadosForm},
				dataType: "json",
				type: "POST",
				success: function(source){
					$.map(source, function (val,i){
					   if(i == 'sucesso'){
						   atualizarGridMetasprofissionais();
					   } 
					});
					tratarMsgRetorno(source);
				}
			});
        });

       
	});
</script>
<?php
//echo("<pre>");
//print_r($this->dados);
//echo("</pre>");
?>

          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title"><div id="moduloCarregado">Formulário - Metas Profissionais</div></h4>
          </div>
          <div class="modal-body">
			<form role="form" id="frmMetasprofissionais" name="frmMetasprofissionais" class="form-horizontal" >

				<input type="hidden" name="metasprofissional_id" id="metasprofissional_id" readonly="readonly" value="<?php echo (isset($this->dados["metasprofissional_id"]) && $this->dados["metasprofissional_id"] > 0)?$this->dados["metasprofissional_id"]:"0"?>"/>
				<input type="hidden" name="metasprofissionais_status" id="metasprofissionais_status" value="Ativo"/>
				<input type="hidden" name="fk_profissionais_id" id="fk_profissionais_id" value="<?php echo (isset($this->fk_profissionais_id))?$this->fk_profissionais_id:"0"?>"/>
				<input type="hidden" name="fk_usuario_id" id="fk_usuario_id" value="<?php echo (isset($this->fk_usuario_id))?$this->fk_usuario_id:"0"?>"/>

				<div class="panel panel-info">
					<div class="panel-body">
						
						<div class="form-group">
								<label class="control-label col-sm-1">Descri&ccedil;&atilde;o:</label>
							<div class="col-md-4">
		                        <input class="form-control" name="metasprofissional_nome" id="metasprofissional_nome" value="<?php echo (isset($this->dados["metasprofissional_nome"]))?$this->dados["metasprofissional_nome"]:""?>"/>
							</div>	
								<label class="control-label col-sm-2">Meta para:</label>
							<div class="col-md-3">
								<input class="form-control" data-date-format="dd/mm/yyyy"  name="data_para_day" id="data_para_day" value="<?php echo (isset($this->dados["day"]))?$this->dados["day"]:""?>"/>
							</div>
							<div class="col-md-2">
								<input class="form-control" name="data_para_hour" id="data_para_hour" value="<?php echo (isset($this->dados["hour"]))?$this->dados["hour"]:""?>"/>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<textarea name="metasprofissional_text" id="metasprofissional_text" class="form-control" rows="15"><?php echo (isset($this->dados['metasprofissional_text']))?$this->dados['metasprofissional_text']:""?></textarea>
							</div>
						</div>
					</div>
				</div>
			</form>
            
          </div>
          <div class="modal-footer">
            <button type="button" data-dismiss="modal" class="btn btn-default">Cancelar</button>
            <button type="button" data-dismiss="modal" class="btn btn-primary" id="salvarMetasprofissionais">Salvar</button>
          </div>

<?php
//}
?>
