<?php 
//Valida a permissão de Visualização
if($this->permissao["status"] == false){
    echo Zend_Json_Encoder::encode($this->permissao);
}else{
    $idRandom = rand(0,999999);
?>
<?php require_once 'js.phtml'; ?>

	<div id="page-wrapper">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    	<div id="moduloCarregado">Metas Profissionais</div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                        	<div class="row">
                                <div class="col-sm-12">
                                    <a id="btnFormularioMetasprofissionais" data-toggle="modal" href="/metasprofissionais/form/metasprofissional_id/0/fk_profissionais_id/<?php echo ($this->idProf); ?>" data-target="#modalMetasProfissionaisNovo" class="btn btn-primary btn-bitbucket">
										<i class="fa fa-filter"></i> Novo</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-metas-profissionais">
                                    <thead>
                                        <tr>
											<th>Gestor</th>
											<th>Data e Hora</th>
											<th>Meta para</th>
											<th>Descri&ccedil;&atilde;o</th>
											
											<th>Upload</th>
											<th>Visualizar</th>
											<th>Alterar</th>
											<th>Excluir</th>
                                    </thead>
                                    <tbody>
									<?php if (isset($this->dados['dados']) && count($this->dados['dados'])) {
										foreach($this->dados['dados'] as $item => $value){ ?>
                                        <tr>
                                            <td><?php echo($value['fk_usuario_id']); ?></td>
                                            <td><?php echo($value['data_creacao']); ?></td>
                                            <td><?php echo($value['data_para']); ?></td>
                                            <td><?php echo($value['metasprofissional_nome']); ?></td>
                                            
                                            <td align="center">
												<?php if ($value['metasprofissional_file'] == "") { ?>
<a name="SelecionarFileMeta[]" id="btnSelecionarFile_<?php echo($value['metasprofissional_id']); ?>_<?php echo($value['metasprofissional_nome']); ?>_<?php echo($value['fk_profissionais_id']); ?>" href="#" class="btn btn-primary btn-xs">
<i class="fa fa-filter"></i> Upload</a>
												<?php } else { ?>
													<a target="_blank" href="<?php echo($value['metasprofissional_file']); ?>">Descarregar</a>
												<?php } ?>                                           
                                            </td>
                                            <td align="center"><a onclick="imprimirMeta('<?php echo($value['metasprofissional_id']); ?>')" href="#"><i class="fa fa-search fa-fw"></i></a></td>
											<td align="center"><a onClick="alterarRegistroGridMetasprofissionais('<?php echo($value['metasprofissional_id']); ?>')" href="#"><i class="fa fa-edit fa-fw" data-toggle="tooltip" data-placement="right" title="Editar"></i></a></td>
                                            <td align="center"><a onclick="excluirRegistroGridMetasprofissionais('<?php echo($value['metasprofissional_id']); ?>')" href="#"><i class="fa fa-eraser fa-fw" data-toggle="tooltip" data-placement="right" title="Excluir"></i></a></td>
                                        </tr>		
									<?php } 
										} ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
        
	</div>



<?php
}
?>
