<?php include 'js.phtml'; ?>

<div class="col-10 ml-sm-auto col-sm-6 col-md-4 ml-md-auto login-center mx-auto">
    <div class="navbar-header text-center">
        <a href="index.html">
            <img alt="" src="assets/demo/logo-expand-dark.png">
        </a>
    </div>
    <h1 class="text-center">ADMIN</h1>
    <!-- /.navbar-header -->
    <form class="form-material form-signin" role="form">
        <div class="form-group">
            <input type="text" placeholder="" class="form-control form-control-line" name="usuario" id="usuario" autofocus>
            <label for="usuario">Usuário</label>
        </div>
        <div class="form-group">
            <input type="password" placeholder="" class="form-control form-control-line" id="senha" name="senha">
            <label for="senha">Senha</label>
        </div>
        <div class="form-group">
            <button id="btnLogin" type="submit" class="btn btn-block btn-lg btn-color-scheme ripple">Entrar</button>
        </div>
        <!-- /.form-group -->
    </form>
    <!-- /.form-material -->
    <!-- /.btn-list -->
</div>
<!-- /.login-center -->
