<script>
    $(function(){
        //$('#senha').keypress(function (e){
            //if(e.keyCode == 13){
             //   $('#btnLogin').click();
            //}
        //});
        $('#btnLogin').click(function (e){
			
			e.preventDefault();
			
            var form = _getFieldsContainer('form');
            
            
            
            $.ajax({
                url: '/admin_login/auth',
                data: {dados:form},
                dataType: "json",
                type: "POST",
                success: function(source){
                     $.map(source, function (val,i){
                        if(i == 'status_login' && val == 'liberado')
                            window.location.href = '/admin_usuarios';
                        if(i == 'erro'){
                            tratarMsgRetorno(source);
                        } 
                     });
                },
                error: function(source){
                    console.log(source);
                }
            });
        });
        
        $('#usuario').focus();
    });
</script>
