<?php
if (!empty($this->dados['dados'])) {

$date_ini = new DateTime($this->params['data_ini']);
$date_fim = new DateTime($this->params['data_fim']);

    $html = $this->doctype();
    $html .= '
        <html lang="pt-Br">
            <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                <title>SAD</title>
            </head>

            <body> 
				<div id="cabecalho">
					<table border="0" width="100%">
                        <thead>                      
                            <tr>
                                <td style="width=100%">
                                    <img src="/imagens/logo.png">
                                </td>
                            </tr>
                            <tr>
                                <td style="width=100%">
                                    &nbsp;
                                </td>
                            </tr>
                            
                        </thead>
                    </table>
                    <table border="0" width="100%">
                        <thead>                      
                            <tr>
                                <td style="text-align: center; font-size:11px; width=100%">
                                    
                                    <b>RELATÓRIO MELHORES PROFISSIONAIS X FUNÇÃO</b> 
                                </td>
                            </tr>
                             <tr>
                                <td style="text-align: center; font-size:11px; width=100%">   
                                    DATA: '.$date_ini->format('d/m/Y').' À '.$date_fim->format('d/m/Y').'. 
                                </td>
                            </tr>
                            
                        </thead>
                    </table>

                </div>
                <table id="gridRelat" class="ui-widget-content ui-corner-all" style="width: 100%;">
                    <thead>
                        <tr class="ui-widget-header" height="50px"  style="padding: 10px 10px 10px 10px">
                            <th style="width:15%">
                                Unidade
                            </th>
                            <th style="width:25%">
                                Nome
                            </th>
                            <th style="width:25%">
                                Função
                            </th>
                            <th style="width:10%">
                                Nota
                            </th>
                       </tr>
                    </thead>
                    <tbody id="dadosGridRelat">';
    
                    $aux = 0;

                    foreach ($this->dados['dados'] as $item) {

                        if ($aux == 0){
                            $cor = '#f7f8f8';
                            $aux = 1;
                        } else {
                            $cor = '#ffffff';
                            $aux = 0;
                        }
                        
                        
                        
                        $html .='<tr style="background:'.$cor.'">
                                    <td style="text-align: center">'.$item['unidades_nome'].'</td>
                                    <td style="text-align: center">'.$item['profissionais_nome'].'</td>
                                    <td style="text-align: center"> '.$item['funcoes_descricao'].'</td>
                                    <td style="text-align: center"> '.$item['media'].'</td>
                                 </tr>';

                    };
                    
            
           $html .='            
                </table>
				<table border="0" width="100%;">
					<thead>
						<tr>
							<td colspan="3">&nbsp;</td>
						</tr>
						<tr>
							<td colspan="3" style="border-top: solid 1px black;"></td>
						</tr>
						<tr>
							<td style="width=33%; font-size:10px;">'.date("d/m/Y").'</td>
							<td style="width=33%"></td>
							<td style="width=33%; font-size:10px;text-align:right;">Sistema Mérito - www.srvdesk.com.br (62) 3933 - 3375
</td>
						</tr>
						
					</thead>
				</table>
           </body>
        </html>';

	echo ($html);
} else {
    echo '<script type="text/javascript" charset="utf-8">javascript:alert(\''.utf8_decode($this->dados['alerta']).'\');javascript:window.close();</script>';
    exit(0);
}
?>

