
<script>

var var_data = '<?php echo($this->data); ?>' ;

montarTabelaAvaliacoesDiaProfissionalDATA(<?php echo $this->dados; ?>, '<?php echo($this->data); ?>')

</script>

  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<h4 class="modal-title">Detalhes da Avaliaçao</h4>
  </div>
  <div class="modal-body">
	<table width="100%" id="lista-atruibuicoes-dia"></table>
  </div>
