
<script>
    $(function(){
        $('#getFiltros').click(function (e){
			e.preventDefault();
			var dadosForm = arrayToObject( $('#frmFiltrosProfissionais').serializeArray() );
			window.location.href =  '/profissionais/index/profissionais_id/'+dadosForm.profissionais_id+'/profissionais_nome/'+dadosForm.profissionais_nome+'/fk_unidades_id/'+dadosForm.fk_unidades_id+'/profissionais_status/'+dadosForm.profissionais_status+'/';
        });
    });
</script>

  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<h4 class="modal-title"><div id="moduloCarregado">Filtro - Profissionais</div></h4>
  </div>
  <div class="modal-body">
	<form role="form" id="frmFiltrosProfissionais" name="frmFiltrosProfissionais" class="form-horizontal">

		<div class="panel-body">
			<div class="form-group">
					<label class="control-label col-sm-2">Código:</label>
				<div class="col-md-10">
					<input class="form-control" type="text" name="profissionais_id" id="profissionais_id"/>
				</div>	
			</div>			
			<div class="form-group">
					<label class="control-label col-sm-2">Nome:</label>
				<div class="col-md-10">
					<input class="form-control" type="text" name="profissionais_nome" id="profissionais_nome"/>
				</div>	
			</div>			
			<div class="form-group">
					<label class="control-label col-sm-2">Unidade:</label>
				<div class="col-md-10">
                      <select class="form-control" name="fk_unidades_id" id="fk_unidades_id">
                      <option>Selecione uma unidade</option>
                      <?php
                        if(sizeof($this->unidades) > 0){
                        foreach($this->unidades as $key=>$unidade){
                        $selected = ($unidade["unidades_id"] == $this->dados['fk_unidades_id'])?"selected='selected'":"";
                        echo "<option value='".$unidade["unidades_id"]."' ".$selected.">".$unidade["unidades_nome"]."</option>";
                                 }
                            }
                        ?>
                      </select>
				</div>	
			</div>

			<div class="form-group">
					<label class="control-label col-sm-2">Função:</label>
				<div class="col-md-10">
                   <select class="form-control" name="fk_funcoes_id" id="fk_funcoes_id">
                      <option>Selecione uma função</option>
                          <?php
                             if(sizeof($this->funcoes) > 0){
                             foreach($this->funcoes as $key=>$funcoes){
                             $selected = ($funcoes["funcoes_id"] == $this->dados['fk_funcoes_id'])?"selected='selected'":"";
                             echo "<option value='".$funcoes["funcoes_id"]."' ".$selected.">".$funcoes["funcoes_descricao"]."</option>";
                                  }
                              }
                          ?>
                    </select>
				</div>	
			</div>	

			<div class="form-group">
					<label class="control-label col-sm-2">Status:</label>
				<div class="col-md-10">
                <select class="form-control" name="profissionais_status" id="profissionais_status">
                    <option value="">Todos</option>
                    <option value="Ativo">Ativo</option>
                    <option value="Bloqueado">Bloqueado</option>
                </select>
				</div>	
			</div>	

		</div>
	</div>
	</form>
  </div>
  <div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	<button type="button" class="btn btn-primary" id="getFiltros">Pesquisar</button>
  </div>
