
<div>
    <form name="frmSalarioEmpregado" id="frmSalarioEmpregado">
            <table style="width: 100%">
                <tr>
                    <td style="width: 10%">Salário:</td>
                    <td>
			<?php echo ($this->salario); ?>
                    </td>
               <td style="width: 10%">Alimentação:</td>
                    <td>
                        <?php echo ($this->alimentacao); ?>
                    </td>
                </tr>
           <tr>
                    <td style="width: 10%">Transporte:</td>
                    <td>
			<?php echo ($this->transporte); ?>
                    </td>
               <td style="width: 10%">Impostos:</td>
                    <td>
                        <?php echo ($this->imposto); ?>
            </td>
                </tr>
            </table>
    </form>
</div>

