<script>
    var idRandom = <?php echo $idRandom?>;
    //Esta variável controla quando vai ser selecionado o formulário para novo registro ou alterar registros
    var idFormFuncoes = 0

	var tfTable ;

    $(document).ready(function() {
		
		$(document).on("hidden.bs.modal", function (e) {
			$(e.target).removeData("bs.modal").find(".modal-content").empty();
		});
		
    	tfTable = $('#dataTables-funcoes').dataTable({
			"bPaginate": true,
			"iDisplayLength" : 10,
			"sPaginationType": "full_numbers",
			"oLanguage": {
				"sLengthMenu":   "Mostrar&nbsp; _MENU_ &nbsp;registros",
				"sZeroRecords":  "N&atilde;o foram encontrados resultados",
				"sInfo": "Mostrando registros de _START_ a _END_ de um total de _TOTAL_ registros",
				"sInfoEmpty": "Nenhum registro para exibir",
				"sSearch" : "Pesquisar:&nbsp; ",
				"sInfoFiltered": "(filtrado de _MAX_ registros no total)",
				"oPaginate": {
				"sFirst":    null,
				"sPrevious": "Anterior",
				"sNext":     "Seguinte",
				"sLast":     null
				}

			}
		});

    });

    function alterarRegistroGridFuncoes(idSelecionado){
        idFormFuncoes = idSelecionado;
        
        $("a[id='btnFormularioFuncoes']").attr("href", '/funcoes/form/funcoes_id/'+idSelecionado+'/<?php echo ((isset($this->tipo)?'tipo/'.$this->tipo.'/':"")); ?>');
        $("a[id='btnFormularioFuncoes']").click();
        
    }

    function excluirRegistroGridFuncoes(idSelecionado){
        if(confirm("Deseja mesmo excluir o registro selecionado?")){
            var obj = new Object();
            obj.id = idSelecionado;
            $.ajax({
                url: "/funcoes/excluir",
                data:  obj,
                dataType: "json",
                type: "POST",
                success: function(source){
                    $.map(source, function (val,i){
                       if(i == 'sucesso'){
                       		window.location.href = '/funcoes';
                       } 
                    });
                    tratarMsgRetorno(source);
                }
            });
        }
    }

    
</script>
