<?php 
//Valida a permissão de Visualização
if($this->permissao["status"] == false){
    echo Zend_Json_Encoder::encode($this->permissao);
}else{
    $idRandom = rand(0,999999);
?>
<?php require_once 'js.phtml'; ?>

<div id="page-wrapper">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		<h4 class="modal-title"><div id="moduloCarregado">Atribuições</div></h4>
	</div>
	<div class="modal-body">
		<div class="row">
			<form role="form" id="frmFuncoesAtribuicoes" name="frmFuncoesAtribuicoes" onsubmit="return false;" class="form-horizontal">

				<input type="hidden" name="funcoes_atribuicoes_id" id="funcoes_atribuicoes_id" value="0"/>
				<input type="hidden" name="fk_funcoes_id" id="fk_funcoes_id" value="<?php echo $this->fk_funcoes_id?>"/>
				<div class="form-group">
						<label class="control-label col-sm-2">Função:</label>
					<div class="col-md-8">
						<input disabled="disabled" class="form-control" value="<?php echo $this->funcao?>"/>
					</div>	
				</div>
				<div class="form-group">
						<label class="control-label col-sm-2">Atribuições:</label>
					<div class="col-md-8">

						<select class="form-control" name="fk_atribuicoes_id" id="fk_atribuicoes_id">
							<option value="">Selecione a atribuição desejada.</option>
							<?php
								if(sizeof($this->dados['atribuicoes']) > 0){
									foreach($this->dados['atribuicoes'] as $meta){
										echo "<option value='".$meta['atribuicoes_id']."'>".$meta["atribuicoes_nome"]."</option>";
									}
								}
							?>
						</select>
					</div>
					<div class="col-md-2" style="padding-top: 5px;">
						<a href="#" id="btnAdicionarFuncoesAtribuicoes"><i class="fa fa-plus fa-fw"></i></a></button>
					</div>
				</div>
			
			</form>
		</div>
	</div>
	<div class="modal-body">
		<div class="row">
			<div class="well">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="dataTables-funcoes-atribuicoes">
						<thead>
							<tr>
								<th>Código</th>
								<th>Descrição</th>
								<th>Alterar</th>
								<th>Excluir</th>
							</tr>
						</thead>
						<tbody>
						<?php if (isset($this->dados2['dados']) && count($this->dados2['dados'])) {
							foreach($this->dados2['dados'] as $item => $value){ ?>
							<tr>
								<td><?php echo($value['fk_atribuicoes_id']); ?></td>
								<td><?php echo($value['atribuicoes_nome']); ?></td>
								<td align="center"><a onclick="alterarRegistroGridFuncoesAtribuicoes('<?php echo($value['funcoes_atribuicoes_id']); ?>', '<?php echo($value['fk_atribuicoes_id']); ?>')" href="#"><i class="fa fa-edit fa-fw" data-toggle="tooltip" data-placement="right" title="Editar"></i></a></td>
								<td align="center"><a onclick="excluirRegistroGridFuncoesAtribuicoes('<?php echo($value['funcoes_atribuicoes_id']); ?>')" href="#"><i class="fa fa-eraser fa-fw" data-toggle="tooltip" data-placement="right" title="Excluir"></i></a></td>
							</tr>		
						<?php } 
							} ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<?php
}
?>
