<?php 
//Valida a permissão de Visualização
if($this->permissao["status"] == false){
    echo Zend_Json_Encoder::encode($this->permissao);
}else{
    $idRandom = rand(0,999999);
?>
<?php require_once 'js.phtml'; ?>

<div id="page-wrapper">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		<h4 class="modal-title"><div id="moduloCarregado">Metas</div></h4>
	</div>
	<div class="modal-body">
		<div class="row">
			<form role="form" id="frmFuncoesMetas" name="frmFuncoesMetas" onsubmit="return false;" class="form-horizontal">

					<input type="hidden" name="funcoes_metas_id" id="funcoes_metas_id" value="0"/>
					<input type="hidden" name="fk_funcoes_id" id="fk_funcoes_id" value="<?php echo $this->fk_funcoes_id?>"/>

				
					<div class="form-group">
							<label class="control-label col-sm-2">Função:</label>
						<div class="col-md-8">
							<input disabled="disabled" class="form-control" value="<?php echo $this->funcao?>"/>
						</div>	
					</div>
					<div class="form-group">
							<label class="control-label col-sm-2">Metas:</label>
						<div class="col-md-4">
							<select class="form-control" name="fk_metas_id" id="fk_metas_id">
								<option value="">Selecione a meta desejada.</option>
								<?php
									if(sizeof($this->dados['metas']) > 0){
										foreach($this->dados['metas'] as $meta){
											echo "<option value='".$meta['metas_id']."'>".$meta["metas_nome"]."</option>";
										}
									}
								?>
							</select>
						</div>
							<label class="control-label col-sm-2">Qtde:</label>
						<div class="col-md-2">
							<input type="text" class="form-control" name="funcoes_metas_qtde" id="funcoes_metas_qtde" value="0" maxlength="4"/>
						</div>
						<div class="col-md-1" style="padding-top:8px ;">
							<a href="#" id="btnAdicionarFuncoesMetas"><i class="fa fa-plus fa-fw"></i></a></button>
						</div>
					</div>
				
			</form>
		</div>
	</div>
	<div class="modal-body">	
		<div class="row">
			<div class="well">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="dataTables-funcoes-metas">
						<thead>
							<tr>
								<th>Código</th>
								<th>Descrição</th>
								<th>Qtde</th>
								<th>Alterar</th>
								<th>Excluir</th>
							</tr>
						</thead>
						<tbody>
						<?php if (isset($this->dados['var']) && count($this->dados['var'])) {
							foreach($this->dados['var'] as $item => $value){ ?>
							<tr>
								<td><?php echo($value['fk_metas_id']); ?></td>
								<td><?php echo($value['metas_nome']); ?></td>
								<td><?php echo($value['funcoes_metas_qtde']); ?></td>
								<td align="center"><a href="#" onclick="alterarRegistroGridFuncoesMetas('<?php echo($value['funcoes_metas_id']); ?>', '<?php echo($value['fk_metas_id']); ?>', '<?php echo($value['funcoes_metas_qtde']); ?>')"><i class="fa fa-edit fa-fw" data-toggle="tooltip" data-placement="right" title="Editar"></i></a></td>
								<td align="center"><a href="#" onclick="excluirRegistroGridFuncoesMetas('<?php echo($value['funcoes_metas_id']); ?>')"><i class="fa fa-eraser fa-fw" data-toggle="tooltip" data-placement="right" title="Excluir"></i></a></td>
							</tr>		
						<?php } 
							} ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>


<?php
}
?>
