<?php 
//Valida a permissão de Visualização
if($this->permissao["status"] == false){
    echo '<p class="msgPermissao alerta">'.$this->permissao["mensagem"].'</p>';
}else{
   $idRandom = rand(0, 999999);
?>
<script>
var idRandom = <?php echo $idRandom?>;
$(function(){
    ///-- *************************
    ///-- Grid de Dados
    ///-- *************************
    ///-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    atualizarGridAutonomosHistorico(null);
    $("#gridAutonomosHistorico"+idRandom).kendoGrid({
        dataSource: {
          type: "odata",
          transport: {
              read: {	

              }
          },
          pageSize: 5
        },
        rowTemplate: kendo.template($("#rowTemplateAutonomosHistorico"+idRandom).html()),
        pageable: {
            refresh: true,
            pageSizes: true
        }
    });

    ///-- Tooltip 
   $("#gridAutonomosHistorico"+idRandom).kendoTooltip({
        filter: "a",
        position: "top"
    }).data("kendoTooltip");
    
    $('button[id^="btnAdicionarAutonomosHistorico"]').click(function (){
        var id = $('input[id^="autonomos_historico_id"]').val();
        var data = $('input[id^="autonomos_historico_data"]').val();
        var descricao = $('input[id^="autonomos_historico_descricao"]').val();
        var autonomos_id = $('input[id^="autonomos_id"]').val();
        $.ajax({
            url: "autonomos-historico/salvar",
            data: {
                    autonomos_historico_id: id, 
                    autonomos_historico_data: data, 
                    autonomos_historico_descricao: descricao,
                    fk_autonomos_id: autonomos_id
                  },
            dataType: "json",
            type: "POST",
            success: function(source){
                $.map(source, function (val,i){
                   if(i == 'sucesso'){
                       $('input[id^="autonomos_historico_id"]').val(0);
                       $('input[id^="autonomos_historico_data"]').val('');
                       $('input[id^="autonomos_historico_descricao"]').val('');
                       atualizarGridAutonomosHistorico(null);
                   } 
                });
                tratarMsgRetorno(source);
            }
        });
    });
    
});

function alterarRegistroAutonomosHistoricoGrid(autonomos_historico_id){
    $.ajax({
        url: "autonomos-historico/get-historico-pelo-id",
        data: { autonomos_historico_id: autonomos_historico_id },
        dataType: "json",
        type: "POST",
        success: function(source){
            if(typeof source.erro != "undefined" || typeof source.alerta != "undefined")
                tratarMsgRetorno(source);
            else{
                var arr = source.dados[0].autonomos_historico_data.split('-');
                $('input[id^="autonomos_historico_id"]').val(autonomos_historico_id);
                $('input[id^="autonomos_historico_data"]').val(arr[2]+'/'+arr[1]+'/'+arr[0]);
                $('input[id^="autonomos_historico_descricao"]').val(source.dados[0].autonomos_historico_descricao);
                atualizarGridAutonomosHistorico(null);
            }
        }
    });
}

function excluirRegistroAutonomosHistoricoGrid(autonomos_historico_id){
    if(confirm("Deseja mesmo excluir este registro?")){
        $.ajax({
            url: "autonomos-historico/excluir",
            data: { id: autonomos_historico_id },
            dataType: "json",
            type: "POST",
            success: function(source){
                tratarMsgRetorno(source);
                atualizarGridAutonomosHistorico(null);
            }
        });
    }
}

function atualizarGridAutonomosHistorico(dados){
    $.ajax({
        url: "autonomos-historico/pesquisar/fk_autonomos_id/"+$('input[id^="autonomos_id"]').val(),
        data: dados,
        dataType: "json",
        type: "POST",
        success: function(source){
            $("#gridAutonomosHistorico"+idRandom).data("kendoGrid").dataSource.data([]);
            var viewModel = new kendo.observable(source);
            $("#gridAutonomosHistorico"+idRandom).data("kendoGrid").dataSource.data(viewModel.dados);
        }
    });
}
</script>
<div>
    <form name="frmAutonomos" id="frmAutonomos" enctype="multipart/form-data">
        <input type="hidden" name="autonomos_id" id="autonomos_id" readonly="readonly" value="<?php echo (isset($this->dados["autonomos_id"]) && $this->dados["autonomos_id"] > 0)?$this->dados["autonomos_id"]:"0"?>"/>
        <input type="hidden" name="autonomos_tipo" id="autonomos_tipo" readonly="readonly" value="<?php echo $this->autonomos_tipo; ?>"/>
        <div id="tabstrip" style="display: none; background: #fff; border: none; margin: 3px; padding: 3px">
            <ul>
                <li class="k-state-active">Dados Pessoais</li>
<?php /* ?>     
				<li>Acessos</li> 
<?php */ ?>
                <li <?php echo ((isset($this->dados["autonomos_id"]) && $this->dados["autonomos_id"] > 0))?"":"style='display: none'"?>>Salário</li>
                <li <?php echo ((isset($this->dados["autonomos_id"]) && $this->dados["autonomos_id"] > 0))?"":"style='display: none'"?>>Foto Profissional</li>
                <li <?php echo ((isset($this->dados["autonomos_id"]) && $this->dados["autonomos_id"] > 0))?"":"style='display: none'"?>>Histórico</li>
            </ul>
            
            <!-- Dados Pessoais -->
            <div>
                <fieldset class="fd-form"><legend>Dados Pessoais:</legend>
                    <table style="width: 100%">
                        <tr>
                            <td>Unidade:</td>
                            <td colspan="3">
                                <select name="fk_unidades_id" id="fk_unidades_id" style="width: 100%">
                                    <option>Selecione uma unidade</option>
                                    <?php
                                        if(sizeof($this->unidades) > 0){
                                            foreach($this->unidades as $key=>$unidade){
                                                $selected = ( isset($this->dados['fk_unidades_id']) && $unidade["unidades_id"] == $this->dados['fk_unidades_id'])?"selected='selected'":"";
                                                echo "<option value='".$unidade["unidades_id"]."' ".$selected.">".$unidade["unidades_nome"]."</option>";
                                            }
                                        }
                                    ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 12%">Nome:</td>
                            <td><input class="k-textbox" maxlength="100" type="text" name="autonomos_nome" id="autonomos_nome" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_nome"]))?$this->dados["autonomos_nome"]:""?>"/></td>
                            <td>Data Nasc:</td>
                            <td><input type="text" name="autonomos_data_nascimento" maxlength="10" style="width: 100%" id="autonomos_data_nascimento" value="<?php echo (isset($this->dados["autonomos_data_nascimento"]))?$this->dados["autonomos_data_nascimento"]:""?>"/></td>                            
<!--                            <td style="width: 12%">Data Adm:</td>
                            <td><input type="text" name="autonomos_data_admissao" maxlength="10" style="width: 100%" id="autonomos_data_admissao" value="<?php echo (isset($this->dados["autonomos_data_admissao"]))?$this->dados["autonomos_data_admissao"]:""?>"/></td>-->
                        </tr>
                        <tr>
                            <td>CPF:</td>
                            <td><input class="k-textbox" type="text" name="autonomos_cpf" maxlength="14" style="width: 100%" id="autonomos_cpf" value="<?php echo (isset($this->dados["autonomos_cpf"]))?$this->dados["autonomos_cpf"]:""?>"/></td>
                            <td>Sexo:</td>
                            <td>
                                <select name="autonomos_sexo" id="autonomos_sexo" style="width: 100%">
                                    <option>Selecione uma opção</option>
                                    <option value='F' <?php echo (isset($this->dados['autonomos_sexo']) && $this->dados['autonomos_sexo'] == 'F')?"selected='selected'":""?>>Feminino</option>
                                    <option value='M' <?php echo (isset($this->dados['autonomos_sexo']) && $this->dados['autonomos_sexo'] == 'M')?"selected='selected'":""?>>Masculino</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>CNPJ:</td>
                            <td><input class="k-textbox" type="text" name="autonomos_cnpj" maxlength="14" style="width: 100%" id="autonomos_cnpj" value="<?php echo (isset($this->dados["autonomos_cnpj"]))?$this->dados["autonomos_cnpj"]:""?>"/></td>
                            <td>RG:</td>
                            <td><input class="k-textbox" type="text" name="autonomos_rg" maxlength="30" style="width: 100%" id="autonomos_rg" value="<?php echo (isset($this->dados["autonomos_rg"]))?$this->dados["autonomos_rg"]:""?>"/></td>
                        </tr>
                        <tr>
                            <td>Função:</td>
                            <td>
                                <select name="fk_funcoes_id" id="fk_funcoes_id" style="width: 100%">
                                    <option>Selecione uma função</option>
                                    <?php

                                        if(sizeof($this->funcoes) > 0){
                                            foreach($this->funcoes as $key=>$funcoes){
                                                $selected = ( (isset($this->dados['fk_funcoes_id'])) && $funcoes["funcoes_id"] == $this->dados['fk_funcoes_id'])?"selected='selected'":"";
                                                echo "<option value='".$funcoes["funcoes_id"]."' ".$selected.">".$funcoes["funcoes_descricao"]."</option>";
                                            }
                                        }
                                    ?>
                                </select>
                            </td>
                            <td>Email:</td>
                            <td><input class="k-textbox" type="text" maxlength="100" name="autonomos_email" id="autonomos_email" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_email"]))?$this->dados["autonomos_email"]:""?>"/></td>
                        </tr>
                        <tr>
                            <td>Obs:</td>
                            <td colspan="3"><textarea name="autonomos_obs" id="autonomos_obs" class="k-textbox" style="width: 100%"><?php echo (isset($this->dados['autonomos_obs']))?$this->dados['autonomos_obs']:""?></textarea></td>
                        </tr>
                        <tr>
                            <td>Titulo Eleitor:</td>
                            <td><input class="k-textbox" type="text" name="autonomos_eleitor" maxlength="50" style="width: 100%" id="autonomos_eleitor" value="<?php echo (isset($this->dados["autonomos_eleitor"]))?$this->dados["autonomos_eleitor"]:""?>"/></td>
                            <td>Recibo IRPF/Ano:</td>
                            <td><input class="k-textbox" type="text" name="autonomos_recibo" maxlength="30" style="width: 100%" id="autonomos_recibo" value="<?php echo (isset($this->dados["autonomos_recibo"]))?$this->dados["autonomos_recibo"]:""?>"/></td>
						</tr>
                        <tr>
                            <td>Filia&ccedil;&atilde;o:</td>
                            <td colspan="3"><textarea name="autonomos_filiacao" id="autonomos_filiacao" class="k-textbox" style="width: 100%"><?php echo (isset($this->dados['autonomos_filiacao']))?$this->dados['autonomos_filiacao']:""?></textarea></td>
                        </tr>						
                        <tr>
                            <td>Data Entrada:</td>
                            <td><input type="text" name="autonomos_dentrada" maxlength="10" style="width: 100%" id="autonomos_dentrada" value="<?php echo (isset($this->dados["autonomos_dentrada"]))?$this->dados["autonomos_dentrada"]:""?>"/></td>
                            <td>Data Saida:</td>
                            <td><input type="text" name="autonomos_dsaida" maxlength="10" style="width: 100%" id="autonomos_dsaida" value="<?php echo (isset($this->dados["autonomos_dsaida"]))?$this->dados["autonomos_dsaida"]:""?>"/></td>
						</tr>

                    </table>
                </fieldset>
                <fieldset class="fd-form"><legend>Telefones</legend>
                    <table width='100%'>
                        <tr>
                            <td style="width: 12%">Fixo 1:</td>
                            <td><input class="k-textbox" type="text" name="autonomos_fixo_1" maxlength="15" id="autonomos_fixo_1" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_fixo_1"]))?$this->dados["autonomos_fixo_1"]:""?>"/></td>
                            <td>Fixo 2:</td>
                            <td><input class="k-textbox" type="text" maxlength="15" name="autonomos_fixo_2" id="autonomos_fixo_2" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_fixo_2"]))?$this->dados["autonomos_fixo_2"]:""?>"/></td>
                        </tr>
                        <tr>
                            <td>Cel 1:</td>
                            <td><input class="k-textbox" type="text" name="autonomos_cel_1" maxlength="15" id="autonomos_cel_1" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_cel_1"]))?$this->dados["autonomos_cel_1"]:""?>"/></td>
                            <td>Cel 2:</td>
                            <td><input class="k-textbox" type="text" maxlength="15" name="autonomos_cel_2" id="autonomos_cel_2" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_cel_2"]))?$this->dados["autonomos_fixo_2"]:""?>"/></td>
                        </tr>
                    </table>
                </fieldset>
                <fieldset class="fd-form"><legend>Endereço:</legend>
                    <table style="width: 100%">
                        <tr>
                            <td style="width: 12%">CEP:</td>
                            <td><input class="k-textbox" type="text" maxlength="10" name="autonomos_cep" id="autonomos_cep" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_cep"]))?$this->dados["autonomos_cep"]:""?>"/></td>
                            <td>Bairro:</td>
                            <td><input class="k-textbox" type="text" maxlength="50" name="autonomos_bairro" id="autonomos_bairro" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_bairro"]))?$this->dados["autonomos_bairro"]:""?>"/></td>
                        </tr>
                        <tr>
                            <td>Logradouro:</td>
                            <td><input class="k-textbox" type="text" maxlength="100" name="autonomos_logradouro" id="autonomos_logradouro" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_logradouro"]))?$this->dados["autonomos_logradouro"]:""?>"/></td>
                            <td>Complemento:</td>
                            <td><input class="k-textbox" type="text" maxlength="100" name="autonomos_complemento" id="autonomos_complemento" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_complemento"]))?$this->dados["autonomos_complemento"]:""?>"/></td>
                        </tr>
                        <tr>
                            <td>UF:</td>
                            <td>
<input class="k-textbox" type="text" maxlength="100" name="autonomos_uf" id="autonomos_uf" style="width: 100%" value="<?php echo (isset($this->dados["autonomos_uf"]))?$this->dados["autonomos_uf"]:""?>"/>
                            </td>
                            <td>Cidade:</td>
                            <td>
<input class="k-textbox" type="text" maxlength="100" name="fk_municipios_codigo_ibge" id="fk_municipios_codigo_ibge" style="width: 100%" value="<?php echo (isset($this->dados["fk_municipios_codigo_ibge"]))?$this->dados["fk_municipios_codigo_ibge"]:""?>"/>
                            </td>
                        </tr>
                    </table>
                </fieldset>
                <fieldset class="fd-form"><legend>Outros</legend>
                    <table width='100%'>
                        <tr>
                            <td style="width: 12%">Status:</td>
                            <td style="width: 36%">
                                <select name="autonomos_status" id="autonomos_status" style="width: 100%">
                                    <option value="Ativo" <?php echo (isset($this->dados["autonomos_status"]) && $this->dados["autonomos_status"] == 'Ativo')?"selected='selected'":""?>>Ativo</option>
                                    <option value="Bloqueado" <?php echo (isset($this->dados["autonomos_status"]) && $this->dados["autonomos_status"] == 'Bloqueado')?"selected='selected'":""?>>Bloqueado</option>
                                </select>
                            </td>
                            <td align="left" style="width: 12%">Senha:</td>
                            <td><input class="k-textbox" maxlength="50" type="password" name="autonomos_senha" id="autonomos_senha" style="width: 100%" value=""/></td>
                        </tr>
                    </table>
                </fieldset>
            </div>
<?php /* ?>            
            <!-- Acessos -->
            <div style="padding: 10px">
                <fieldset class="fd-form"><legend>Profissional</legend>
                    Cargo: 
                    <select name="autonomos_cargo" id="autonomos_cargo">
                        <option value="funcionario" <?php echo (isset($this->dados['autonomos_cargo']) && $this->dados['autonomos_cargo'] == 'funcionario')?"selected='selected'":""?>>Funcionário</option>
                        <option value="administrador" <?php echo (isset($this->dados['autonomos_cargo']) && $this->dados['autonomos_cargo'] == 'administrador')?"selected='selected'":""?>>Administrador</option>
                        <option value="gerente" <?php echo (isset($this->dados['autonomos_cargo']) && $this->dados['autonomos_cargo'] == 'gerente')?"selected='selected'":""?>>Gerente</option>
                    </select>
                </fieldset>
                <fieldset class="fd-form"><legend>Permissões</legend>
                    <?php
                        if(isset($this->permissoes) && sizeof($this->permissoes) > 0){
                            echo '<ul id="panelbar">';
                            $ultimaPermissao = '';

                            foreach($this->permissoes as $permissao){
                                if($ultimaPermissao != $permissao["permissoes_modulo"]){
                                    if($ultimaPermissao != ''){
                                        echo '</ul></li>';
                                    }
                                    $ultimaPermissao = $permissao["permissoes_modulo"];
                                    echo '<li>'.$permissao["permissoes_modulo"];
                                    echo    '<ul>';
                                }
                                $selected = '';
                                reset($this->autonomos_permissoes);
                                foreach($this->autonomos_permissoes as $i){
                                    if($i['permissoes_modulo'] == $permissao['permissoes_modulo'] && $i['permissoes_nome'] == $permissao['permissoes_nome']){
                                        $selected = 'checked="checked"';
                                    }
                                }
                                echo            '<li><input type="checkbox" '.$selected.' id="permissao_'.$permissao['permissoes_id'].'" value="'.$permissao['permissoes_id'].'"/> '.$permissao['permissoes_nome'].'</li>';

                            }
                            echo    '</ul></li>';
                            echo '</ul>';
                        }
                    ?>
                </fieldset>
            </div>
<?php */ ?>            
            <!-- Salário -->
            <div style="padding: 10px">
                <table>
                    <tr>
                        <td>Faturamento Quinzenal:</td>
                        <td><input class="k-textbox" type="text" maxlength="100" name="autonomos_salario" id="autonomos_salario" style="width: 100%" value="<?php echo number_format((isset($this->dados["autonomos_salario"]))?$this->dados["autonomos_salario"]:0,2,",",".")?>"/></td>
                        <td width="15%">Alimentação:</td>
                        <td><input class="k-textbox" type="text" maxlength="100" name="autonomos_alimentacao" id="autonomos_alimentacao" style="width: 100%" value="<?php echo number_format((isset($this->dados["autonomos_alimentacao"]))?$this->dados["autonomos_alimentacao"]:0,2,",",".")?>"/></td>
                    </tr>
                    <tr>
                        <td>Transporte:</td>
                        <td><input class="k-textbox" type="text" maxlength="100" name="autonomos_transporte" id="autonomos_transporte" style="width: 100%" value="<?php echo number_format((isset($this->dados["autonomos_transporte"]))?$this->dados["autonomos_transporte"]:0,2,",",".")?>"/></td>
                        <td>Imposto:</td>
                        <td><input class="k-textbox" type="text" maxlength="100" name="autonomos_impostos" id="autonomos_impostos" style="width: 100%" value="<?php echo number_format((isset($this->dados["autonomos_impostos"]))?$this->dados["autonomos_impostos"]:0,2,",",".")?>"/></td>
                    </tr>
                    <tr>
                        <td>Porcentagem:</td>
                        <td><input class="k-textbox" type="text" maxlength="100" name="autonomos_porcentagem" id="autonomos_porcentagem" style="width: 100%" value="<?php echo number_format((isset($this->dados["autonomos_porcentagem"]))?$this->dados["autonomos_porcentagem"]:0,2,",",".")?>"/></td>
                        <td>Comiss&atilde;o:</td>
                        <td><input class="k-textbox" type="text" maxlength="100" name="autonomos_comissao" id="autonomos_comissao" style="width: 100%" value="<?php echo number_format((isset($this->dados["autonomos_comissao"]))?$this->dados["autonomos_comissao"]:0,2,",",".")?>"/></td>
                    </tr>
                </table>
            </div>
            
            <!-- Fotos Autonomos -->
            <div style="padding: 10px">
                <table width="95%">
                    <tr>
                        <td>
                            <table width="100%">
                                <tr>
                                    <td width="1%">
                                        <input type="button" id="btnSelecionarImagem" value="Selecione a Imagem" class="k-button" />
                                    </td>
                                    <td>
                                        <div id="progressbar" style="border: 1px solid #ccc; background: #fcfcfc; height: 15px"></div>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" id="profissional_img"><img id="img_prof" src="<?php echo (file_exists("imagens/autonomos/profissional_".$this->dados["autonomos_id"].".jpg"))?"imagens/autonomos/profissional_".$this->dados["autonomos_id"].".jpg?rid=".rand(0,9999999)."":"imagens/sem_foto.png"?>" class="imgProfissional"/></td>
                    </tr>
                </table>
            </div>
            
            <!-- Histórico -->
            <div style="padding: 10px">
                <input type="hidden" name="autonomos_historico_id" id="autonomos_historico_id" value="0"/>
                <fieldset class="fd-form">
                    <table>
                        <tr>
                            <td>Data:</td>
                            <td><input type="text" name="autonomos_historico_data" maxlength="10" id="autonomos_historico_data" value=""/></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Descrição:</td>
                            <td style="width: 70%">
                                <input class="k-textbox" type="text" name="autonomos_historico_descricao" id="autonomos_historico_descricao" style="width: 100%"/>
                            </td>
                            <td><button class="k-button" id="btnAdicionarAutonomosHistorico" title="Adicionar Informação"><span class="k-icon k-si-plus"></span> Adicionar</button></td>
                        </tr>
                    </table>
                </fieldset>
                <!-- Grid de dados do módulo -->
                <table id="gridAutonomosHistorico<?php echo $idRandom;?>">
                    <colgroup>
                        <col width="20%"/>
                        <col width="50%"/>
                        <col width="50px"/>
                        <col width="50px"/>
                    </colgroup>
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Descrição</th>
                            <th>Alterar</th>
                            <th>Excluir</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="4"></td>
                        </tr>
                    </tbody>
                </table>
                <script id="rowTemplateAutonomosHistorico<?php echo $idRandom;?>" type="text/x-kendo-tmpl">
                        <tr>
                                <td>#: autonomos_historico_data #</td>
                                <td>#: autonomos_historico_descricao #</td>
                                <td align="center"><a class="k-button" title="Alterar" onclick="alterarRegistroAutonomosHistoricoGrid('#: autonomos_historico_id #')"><span class="k-icon k-i-pencil"></span></a></td>
                                <td align="center"><a class="k-button" title="Excluir" onclick="excluirRegistroAutonomosHistoricoGrid('#: autonomos_historico_id #')"><span class="k-icon k-i-close"></span></a></td>
                       </tr>
                </script>
            </div>
            
        </div>
        <div style="text-align: right">
            <button class="k-button" id="btnSalvar">Salvar</button>
            <button class="k-button" id="btnCancelar">Cancelar</button>
        </div>
    </form>
</div>
<?php 
}
?>
