
<script>
    $(function(){
        $('#getFiltros').click(function (e){
			e.preventDefault();
			var dadosForm = arrayToObject( $('#frmFiltrosUnidades').serializeArray() );
			window.location.href =  '/unidades/index/unidades_id/'+dadosForm.unidades_id+'/unidades_nome/'+dadosForm.unidades_nome+'/unidades_status/'+dadosForm.unidades_status+'/';
        });
    });
</script>

  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<h4 class="modal-title"><div id="moduloCarregado">Filtro - Unidades</div></h4>
  </div>
  <div class="modal-body">
	<form role="form" id="frmFiltrosUnidades" name="frmFiltrosUnidades" class="form-horizontal">
		<input type="hidden" name="unidades_id" id="unidades_id" readonly="readonly" value="<?php echo (isset($this->dados["unidades_id"]) && $this->dados["unidades_id"] > 0)?$this->dados["unidades_id"]:"0"?>"/>

		<div class="panel-body">
			<div class="form-group">
					<label class="control-label col-sm-2">Código:</label>
				<div class="col-md-10">
					<input class="form-control" name="unidades_id" id="unidades_id"/>
				</div>	
			</div>			
			<div class="form-group">
					<label class="control-label col-sm-2">Unidade:</label>
				<div class="col-md-10">
					<input class="form-control" name="unidades_nome" id="unidades_nome"/>
				</div>	
			</div>			
			<div class="form-group">
					<label class="control-label col-sm-2">Status:</label>
				<div class="col-md-10">
					<select class="form-control"  name="unidades_status" id="unidades_status">
						<option value="">Todos</option>
						<option value="Ativo">Ativo</option>
						<option value="Bloqueado">Bloqueado</option>
					</select>
				</div>	
			</div>
		</div>
	</div>
	</form>
  </div>
  <div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	<button type="button" class="btn btn-primary" id="getFiltros">Salvar</button>
  </div>
