<?php 
//Valida a permissão de Visualização
if($this->permissao["status"] == false){
    echo Zend_Json_Encoder::encode($this->permissao);
}else{
   
?>

<link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/jquery.dataTables.min.js"></script>
<?php require_once 'js.phtml'; ?>

<!-- Page Title Area -->
<div class="row page-title clearfix">
    <div class="page-title-left">
        <h5 class="mr-0 mr-r-5">Unidades</h5>
    </div>
</div>
<!-- /.page-title -->
<!-- =================================== -->
<!-- Different data widgets ============ -->
<!-- =================================== -->
<div class="widget-list">
    <div class="row">
        <div class="col-md-12 widget-holder">
            <div class="widget-bg">
                <div class="widget-heading clearfix">
                    <h5>Listagem</h5>
                </div>
                <div>
                    <button class="btn btn-info btn-rounded ripple" onclick="window.location.href = '/unidades/form'"><i class="material-icons list-icon">add</i><span>Novo</span></button>
                    <button href="#" data-toggle="modal" data-target="#modalFiltrosUnidades" class="btn btn-info btn-rounded ripple"><i class="material-icons list-icon">filter_list</i><span>Filtros</span></button>
                </div>
                <!-- /.widget-heading -->
                <div class="widget-body clearfix">
                    <table class="table table-striped table-responsive" id="dataTables-unidades">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Unidade</th>
                                <th>Telefone</th>
                                <th>Endereço</th>
                                <th style="text-align: center;">Colaboradores</th>
                                <th style="text-align: center;">Alterar</th>
                                <th style="text-align: center;">Excluir</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (isset($this->dados['dados']) && count($this->dados['dados'])) {
                                foreach($this->dados['dados'] as $item => $value){ ?>
                                <tr>
                                    <td><?php echo($value['unidades_id']); ?></td>
                                    <td><?php echo($value['unidades_nome']); ?></td>
                                    <td><?php echo($value['unidades_fixo_1']); ?></td>
                                    <td><?php echo($value['unidades_logradouro']); ?></td>
                                    <td align="center"><button type="button" class="btn btn-info btn-circle btn-sm" onclick="mostrarColaboradores('<?php echo($value['unidades_id']); ?>')" ><i class="material-icons list-icon">visibility</i></button></td>
                                    <td align="center"><button type="button" class="btn btn-color-scheme btn-circle btn-sm" onclick="window.location.href = '/unidades/form/unidades_id/<?php echo($value['unidades_id']); ?>/'"><i class="material-icons list-icon">create</i></button></td>
                                    <td align="center"><button type="button" class="btn btn-danger btn-circle btn-sm" href="#" onclick="excluirRegistroGrid('<?php echo($value['unidades_id']); ?>')" ><i class="material-icons list-icon">clear</i></button></td>
                                </tr>       
                            <?php } 
                            } ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.widget-body -->
            </div>
            <!-- /.widget-bg -->
        </div>
        <!-- /.widget-holder -->
    </div>
    <!-- /.row -->
</div>

<script>
    $(function(){
        $('#getFiltros').click(function (e){
            e.preventDefault();
            var dadosForm = arrayToObject( $('#frmFiltrosUnidades').serializeArray() );
            window.location.href =  '/unidades/index/unidades_id/'+dadosForm.unidades_id+'/unidades_nome/'+dadosForm.unidades_nome+'/unidades_status/'+dadosForm.unidades_status+'/';
        });
    });
</script>

<div class="modal fade" id="modalFiltrosUnidades">
  <div class="modal-dialog srvdesk-small-modal">
    <div class="modal-content">
        <div class="modal-header text-inverse">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h5 class="modal-title" id="myMediumModalLabel">Filtros</h5>
        </div>
        <div class="modal-body">
            <form role="form" id="frmFiltrosUnidades" name="frmFiltrosUnidades" class="form-horizontal">
                <input type="hidden" name="unidades_id" id="unidades_id" readonly="readonly" value="<?php echo (isset($this->dados["unidades_id"]) && $this->dados["unidades_id"] > 0)?$this->dados["unidades_id"]:"0"?>"/>
                <div class="form-group">
                        <label class="control-label col-sm-2">Código:</label>
                    <div class="col-md-10">
                        <input class="form-control" name="unidades_id" id="unidades_id"/>
                    </div>  
                </div>          
                <div class="form-group">
                        <label class="control-label col-sm-2">Unidade:</label>
                    <div class="col-md-10">
                        <input class="form-control" name="unidades_nome" id="unidades_nome"/>
                    </div>  
                </div>          
                <div class="form-group">
                        <label class="control-label col-sm-2">Status:</label>
                    <div class="col-md-10">
                        <select class="form-control"  name="unidades_status" id="unidades_status">
                            <option value="">Todos</option>
                            <option value="Ativo">Ativo</option>
                            <option value="Bloqueado">Bloqueado</option>
                        </select>
                    </div>  
                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-info" id="getFiltros">Pesquisar</button>
            </div>
        </div>
    </div>
  </div>
</div>

<?php
}
?>
