<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.1/jquery.toast.min.js"></script>
    <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/js/jquery.maskedinput.min.js'); ?>
    <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/js/principal.js'); ?>

    <link rel="icon" type="image/png" sizes="16x16" href="assets/demo/favicon.png">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Login</title>
    <!-- CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.1/jquery.toast.min.css" rel="stylesheet" type="text/css">
    <link href="assets/vendors/material-icons/material-icons.css" rel="stylesheet" type="text/css">
    <link href="assets/vendors/mono-social-icons/monosocialiconsfont.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.4/sweetalert2.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.1.3/mediaelementplayer.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/0.7.0/css/perfect-scrollbar.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,600,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="assets/css/style.css" rel="stylesheet" type="text/css">
    <!-- Head Libs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
</head>

<body class="body-bg-full profile-page" style="background-image: url(assets/demo/night.jpg)">
    <div id="wrapper" class="row wrapper">
        <?php echo $this->layout()->content ?>
    </div>
    <!-- /.body-container -->
    <!-- Scripts -->
    <script type="text/javascript" src="assets/js/material-design.js"></script>
</body>

</html>

<!-- <?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        
        <?php $this->headLink()->appendStylesheet('http://'.$_SERVER["HTTP_HOST"].'/plugins/tAlert/tAlert.css'); ?>
        
        <?php $this->headLink()->appendStylesheet('http://'.$_SERVER["HTTP_HOST"].'/bootstrap-3.2.0/css/bootstrap.min.css'); ?>
        <?php $this->headLink()->appendStylesheet('http://'.$_SERVER["HTTP_HOST"].'/bootstrap-3.2.0/css/bootstrap-theme.min.css'); ?>
        <?php $this->headLink()->appendStylesheet('http://'.$_SERVER["HTTP_HOST"].'/css/css.css'); ?>
        <?php $this->headLink()->appendStylesheet('http://'.$_SERVER["HTTP_HOST"].'/css/principal.css'); ?>
        
        
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/js/jquery.min.js'); ?>
        <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/bootstrap-3.2.0/js/bootstrap.min.js'); ?>
        <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/js/js.js'); ?>
        <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/plugins/tAlert/tAlert.js'); ?>
        <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/plugins/kendoui/js/kendo.web.min.js'); ?>
        <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/js/jquery.maskedinput.min.js'); ?>
        <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/js/ajaxupload.3.5.js'); ?>
        
        <?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/js/principal.js'); ?>
        
        
    </head>
    <body>
		
        <div id="inputWindow"></div>
        <div class="carregando" style="display: none"></div>
        

<?php echo $this->layout()->content ?>

        <div id="moduloCarregado"></div>
        <div id="botoesModulo"></div>
        <div id="contentPrincipal"></div>
        <div class="alerta-personalizado" id="alerta-personalizado"></div>
    </body>
</html>
  -->

 

