<?php 
$MTarefasProfissionais = new Application_Model_DbTable_TarefasProfissionais();
$MTarefasObservacoes = new Application_Model_DbTable_TarefasObservacoes();

//Valida a permissão de Visualização
if($this->permissao["status"] == false){
    echo '<p class="msgPermissao alerta">'.$this->permissao["mensagem"].'</p>';
}else{
   
?>

<?php echo $this->headScript()->offsetSetFile(1, 'http://'.$_SERVER["HTTP_HOST"].'/js/jquery.maskedinput.min.js'); ?>
<script>
    $(function(){

			$("input[id^='tarefas_fixo'], input[id^='tarefas_cel']").mask("(99) 9999-9999");
			
	    $('#saveTarefa').click(function (e){
				e.preventDefault();

				var dadosForm = arrayToObject( $('#frmTarefas').serializeArray() );
				
				$.ajax({
	                url: '/tarefas/salvarfuncionario',
	                data: {dados:dadosForm},
	                dataType: "json",
	                type: "POST",
	                success: function(source){
	                     $.map(source, function (val,i){
							 
	                        if(i == 'sucesso')
	                            window.location.href = './tarefas';
							if(i == 'erro'){
	                            tratarMsgRetorno(source);
	                        }
	                     });
	                },
	                error: function(source){
						console.log(source);
	                }
	            });
				
	    });

	    $('#saveObs').click(function (e){
				e.preventDefault();

				var dadosForm = arrayToObject( $('#frmObs').serializeArray() );
				
				$.ajax({
	                url: '/tarefas/salvarobservacao',
	                data: {dados:dadosForm},
	                dataType: "json",
	                type: "POST",
	                success: function(source){
	                     $.map(source, function (val,i){
							 
	                        if(i == 'sucesso')
	                            location.reload();
							if(i == 'erro'){
	                            tratarMsgRetorno(source);
	                        }
	                     });
	                },
	                error: function(source){
						console.log(source);
	                }
	            });
				
	    });

    });
</script>

<div class="row page-title clearfix">
    <div class="page-title-left">
        <h5 class="mr-0 mr-r-5">Tarefas</h5>
    </div>
</div>
<div class="widget-list">
  <div class="row">
      <div class="col-md-12 widget-holder">
          <div class="widget-bg">
          		<form role="form" id="frmTarefas" name="frmTarefas" class="form-horizontal">
          				<?php $tarefa_profissional = $MTarefasProfissionais->getRegistros(array('tarefas_profissionais_tarefa_id' => $this->dados["tarefas_id"], 'tarefas_profissionais_profissional_id' => $_SESSION['profissionais_id']))[0] ?>
          				<input type="hidden" name="tarefas_profissionais_id" id="tarefas_id" readonly="readonly" value="<?php echo $tarefa_profissional['tarefas_profissionais_id'] ?>"/>
          				<h5 class="box-title mr-b-0">Informações</h5>
          				<div class="form-group">
										<label for="tarefas_gestor_nome" class="control-label col-sm-2">Gestor:</label>
										<div class="col-sm-10">
											<input disabled class="form-control" id="tarefas_gestor_nome" name="tarefas_gestor_nome" value="<?php echo (isset($this->dados["tarefas_gestor_nome"]))?$this->dados["tarefas_gestor_nome"]:""?>">
										</div>	
									</div>
									<div class="form-group">
										<label for="tarefas_nome" class="control-label col-sm-2">Nome:</label>
										<div class="col-sm-10">
											<input disabled class="form-control" id="tarefas_nome" name="tarefas_nome" value="<?php echo (isset($this->dados["tarefas_nome"]))?$this->dados["tarefas_nome"]:""?>">
										</div>	
									</div>
									<div class="form-group">
										<label for="tarefas_status" class="control-label col-sm-2">Descrição:</label>
										<div class="col-sm-10">
											<textarea disabled class="form-control" id="tarefas_descricao" name="tarefas_descricao" value="<?php echo (isset($this->dados["tarefas_descricao"]))?$this->dados["tarefas_descricao"]:""?>"><?php echo (isset($this->dados["tarefas_descricao"]))?$this->dados["tarefas_descricao"]:""?></textarea>
										</div>
									</div>
									<div class="form-group">
										<label for="tarefas_data_inicio" class="control-label col-sm-2">Data Início:</label>
										<div class="col-sm-10">
											<input disabled class="form-control datepicker" data-date-format="dd/mm/yyyy" type="text" name="tarefas_data_inicio" id="tarefas_data_inicio" value="<?php echo (isset($this->dados["tarefas_data_inicio"]))?$this->dados["tarefas_data_inicio"]:""?>"/>
										</div>	
									</div>
									<div class="form-group">
										<label for="tarefas_data_termino" class="control-label col-sm-2">Data Término:</label>
										<div class="col-sm-10">
											<input disabled class="form-control datepicker" data-date-format="dd/mm/yyyy" type="text" name="tarefas_data_termino" id="tarefas_data_termino" value="<?php echo (isset($this->dados["tarefas_data_termino"]))?$this->dados["tarefas_data_termino"]:""?>"/>
										</div>	
									</div>
									<div class="form-group">
										<label for="tarefas_pontos" class="control-label col-sm-2">Pontos:</label>
										<div class="col-sm-10">
											<input disabled type="number" class="form-control" id="tarefas_pontos" name="tarefas_pontos" value="<?php echo (isset($this->dados["tarefas_pontos"]))?$this->dados["tarefas_pontos"]:""?>">
										</div>	
									</div>
									<div class="form-actions">
										<button type="button" class="btn btn-rounded btn-default" onclick="window.location.href = '/tarefas'">Voltar</button>
				            <?php if($tarefa_profissional['tarefas_profissionais_finalizada']): ?>
				            <strong>PARTICIPAÇÃO CONCLUÍDA</strong>
				            <?php else: ?>
				            <button type="button" class="btn btn-rounded btn-primary" id="saveTarefa">Concluir Participação</button>
				          	<?php endif; ?>
									</div>
          		</form>
          </div>
          <!-- /.widget-bg -->
      </div>

      <div class="col-md-12 widget-holder">
          <div class="widget-bg">
              <div class="widget-body clearfix">
              	<form role="form" id="frmObs" name="frmObs" class="form-horizontal">
              		<input type="hidden" name="tarefas_id" id="tarefas_id" readonly="readonly" value="<?php echo $this->dados["tarefas_id"] ?>"/>
              		<h5 class="box-title mr-b-0">ADICIONAR OBSERVAÇÃO</h5>
              		<div class="form-group">
										<label for="tarefas_observacoes_mensagem" class="control-label col-sm-2">Mensagem:</label>
										<div class="col-sm-10">
											<textarea class="form-control" id="tarefas_observacoes_mensagem" name="tarefas_observacoes_mensagem" rows="5"></textarea>
										</div>	
									</div>
									<div class="form-actions">
				            <button type="button" class="btn btn-rounded btn-primary" id="saveObs">Salvar</button>
									</div>
								</form>
								<?php if((isset($this->dados["tarefas_id"]) && $this->dados["tarefas_id"] > 0)): ?>
									<?php 
									$acabou_tudo = 0; 
									$funcionarios_observacoes = $MTarefasObservacoes->getRegistros(array('tarefas_observacoes_tarefa_id' => $this->dados["tarefas_id"], 'tarefas_profissionais_profissional_id' => $_SESSION['profissionais_id'])); 
									?>
									<h4>Minhas Observações</h4>
									<table class="table table-striped table-bordered table-hover">
										<tr>
											<th>Mensagem</th>
										</tr>
										<?php foreach ($funcionarios_observacoes as $funcionarios_observacao): ?>
										<tr>
											<td><?php echo $funcionarios_observacao['tarefas_observacoes_mensagem'] ?></td>
										</tr>
										<?php endforeach; ?>
									</table>
									<?php endif; ?>
							</div>
					</div>
			</div>
  </div>
</div>

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css?teste" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js?teste"></script>

<script>
$(document).ready(function(){
	setTimeout(function(){
		$('.select2').select2();
	}, 500);
	$('.datepicker').datepicker({
          dateFormat: 'dd/mm/yy',
           dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
           dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
           dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
           monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
           monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
           nextText: 'Proximo',
           prevText: 'Anterior'
        });
});
</script>

<?php
}
?>
