<?php 
//Valida a permissão de Visualização
if($this->permissao["status"] == false){
    echo Zend_Json_Encoder::encode($this->permissao);
}else{
   
?>

<link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/jquery.dataTables.min.js"></script>
<?php require_once 'js.phtml'; ?>
<?php $ids = array() ?>
<!-- Page Title Area -->
<div class="row page-title clearfix">
    <div class="page-title-left">
        <h5 class="mr-0 mr-r-5">Tarefas</h5>
    </div>
</div>
<!-- /.page-title -->
<!-- =================================== -->
<!-- Different data widgets ============ -->
<!-- =================================== -->
<div class="widget-list">
    <div class="row">
        <div class="col-md-12 widget-holder">
            <div class="widget-bg">
                <div class="widget-heading clearfix">
                    <h5>Listagem</h5>
                </div>
                <div>
                    <?php if($_SESSION['profissionais_cargo'] != 'funcionario'): ?>
                    <button class="btn btn-info btn-rounded ripple" onclick="window.location.href = '/tarefas/form'"><i class="material-icons list-icon">add</i><span>Novo</span></button>
                    <?php endif; ?>
                </div>
                <!-- /.widget-heading -->
                <div class="widget-body clearfix">
                    <table class="table table-striped table-responsive" id="dataTables-tarefas">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Tarefa</th>
                                <th>Pontos</th>
                                <th>Situação</th>
                                <th style="text-align: center;">Alterar</th>
                                <?php if($_SESSION['profissionais_cargo'] != 'funcionario'): ?>
                                <th style="text-align: center;">Excluir</th>
                                <?php endif; ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (isset($this->dados['dados']) && count($this->dados['dados'])) {
                                foreach($this->dados['dados'] as $item => $value){ ?>
                                <?php if(in_array($value['tarefas_id'], $ids)) continue; ?>
                                <?php array_push($ids, $value['tarefas_id']) ?>
                                <tr>
                                    <td><?php echo($value['tarefas_id']); ?></td>
                                    <td><?php echo($value['tarefas_nome']); ?></td>
                                    <td><?php echo($value['tarefas_pontos']); ?></td>
                                    <td>
                                        <?php if ($value['tarefas_situacao'] == 'andamento') echo 'Em andamento'; ?>
                                        <?php if ($value['tarefas_situacao'] == 'pendente') echo 'Aguardando Aprovação'; ?>
                                        <?php if ($value['tarefas_situacao'] == 'concluida') echo 'Concluída'; ?>
                                        <?php if ($value['tarefas_situacao'] == 'cancelada') echo 'Cancelada'; ?>
                                     </td>
                                    <td align="center"><button type="button" class="btn btn-color-scheme btn-circle btn-sm" onclick="window.location.href = '/tarefas/<?php echo $_SESSION['profissionais_cargo'] != 'funcionario' ? 'form' : 'formfuncionario' ?>/tarefas_id/<?php echo($value['tarefas_id']); ?>/'"><i class="material-icons list-icon">create</i></button></td>
                                    <?php if($_SESSION['profissionais_cargo'] != 'funcionario'): ?>
                                    <td align="center"><button type="button" class="btn btn-danger btn-circle btn-sm" href="#" onclick="excluirRegistroGrid('<?php echo($value['tarefas_id']); ?>')" ><i class="material-icons list-icon">clear</i></button></td>
                                    <?php endif; ?>
                                </tr>       
                            <?php } 
                                } ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.widget-body -->
            </div>
            <!-- /.widget-bg -->
        </div>
        <!-- /.widget-holder -->
    </div>
    <!-- /.row -->
</div>

<?php
}
?>
