<?php 
//Valida a permissão de Visualização
if($this->permissao["status"] == false){
    echo '<p class="msgPermissao alerta">'.$this->permissao["mensagem"].'</p>';
}else{
   
?>
<div>
    <form name="frmAutonomosMetas" id="frmAutonomosMetas">
        <input type="hidden" name="fk_autonomos_id" id="fk_autonomos_id" value="<?php echo (isset($this->fk_autonomos_id))?$this->fk_autonomos_id:""?>"/>
        <input class="k-textbox" type="hidden" name="autonomos_metas_id" id="autonomos_metas_id" readonly="readonly" value="<?php echo (isset($this->dados["autonomos_metas_id"]) && $this->dados["autonomos_metas_id"] > 0)?$this->dados["autonomos_metas_id"]:"0"?>"/>
        <fieldset class="fd-form"><legend>Dados Gerais:</legend>
            <table style="width: 100%">
                <tr style="font-weight: bold">
                    <td>Profissional:</td>
                    <td><?php echo $this->fk_autonomos_id." - ".(isset($this->autonomos_nome))?$this->autonomos_nome:""?></td>
                </tr>
                <tr>
                    <td>Meta:</td>
                    <td>
                        <select name="fk_metas_id" id="fk_metas_id" style="width: 100%">
                            <option>Selecione uma Meta</option>
                            <?php
                                if(sizeof($this->metas) > 0){
                                    foreach($this->metas as $key=>$metas){
                                        $selected = ($metas["metas_id"] == $this->dados['fk_metas_id'])?"selected='selected'":"";
                                        echo "<option value='".$metas["metas_id"]."' ".$selected.">".$metas["metas_nome"]."</option>";
                                    }
                                }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td style="width: 10%">Cota:</td>
                    <td>
                        <input type="text" name="autonomos_metas_cota" id="autonomos_metas_cota" value="<?php echo (isset($this->dados["autonomos_metas_cota"]))?$this->dados["autonomos_metas_cota"]:"0"?>"/>
                    </td>
                </tr>
                <tr>
                    <td style="width: 10%">Quinzena:</td>
                    <td>
                        <input type="text" name="autonomos_metas_total_quinzena" id="autonomos_metas_total_quinzena" value="<?php echo (isset($this->dados["autonomos_metas_total_quinzena"]))?$this->dados["autonomos_metas_total_quinzena"]:"0"?>"/>
                    </td>
                </tr>
                <tr>
                    <td style="width: 10%">Mês:</td>
                    <td>
                        <input type="text" name="autonomos_metas_total_mes" id="autonomos_metas_total_mes" value="<?php echo (isset($this->dados["autonomos_metas_total_mes"]))?$this->dados["autonomos_metas_total_mes"]:"0"?>"/>
                    </td>
                </tr>
            </table>
        </fieldset>
        <div style="text-align: right">
            <button class="k-button" id="btnSalvarAutonomosMetas">Salvar</button>
            <button class="k-button" id="btnCancelarAutonomosMetas">Cancelar</button>
        </div>
    </form>
</div>
<?php
}
?>
